CREATE TABLE roupa (
	id_roupa INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	descricao VARCHAR(50) NOT NULL,
	preco NUMERIC(10,2) NOT NULL,
	prazo_dias INTEGER NOT NULL,
	ativo BOOLEAN DEFAULT TRUE
);